platform :ios, '8.0'
use_frameworks!

target 'Player Example' do
  pod 'DailymotionPlayerSDK', :path => '../'
end

target 'DailymotionPlayerSDKUITests' do
  pod 'DailymotionPlayerSDK', :path => '../'
end
